#!/bin/sh

acpi_listen | while read -r line; do
	if [ $(pgrep X) != "" ]; then
	case ${line} in
		"button/micmute MICMUTE"* )
			~/.local/scripts/dwm-micmust
			;;
		"jack/headphone HEADPHONE unplug"*)
			playerctl pause
			;;
		"jack/headphone HEADPHONE plug"*)
			playerctl play
			;;
		"jack/microphone MICROPHONE"*)
			~/.local/scripts/dwm-micmust
			;;
	esac
	fi
done

unset line
