#!/bin/sh

bpath="/sys/class/power_supply/BAT0"
bperc="$(cat ${bpath}/capacity)"

case "$(cat ${bpath}/status)" in
	"Charging") status="+";;
	"Discharging") status="";;
	"Not charging") status="❌";;
esac

printf "%s%%%s" "${bperc}" "${status}"

unset bpath
unset bperc
unset status
