#!/bin/sh

vol="$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1 { print $5" "$12 }')"

case "$(pactl get-sink-mute @DEFAULT_SINK@)" in
	"Mute: yes") emo="🔈❌";;
	"Mute: no") emo="🔊";;
esac

printf "%s %s" "${emo}" "${vol}"
unset emo vol
