#!/bin/sh
# Shamelessly copied from Luke Smith

location=""
cache="${XDG_CACHE_HOME:-${HOME}/.cache}/wttr_cache"

if [ ! -s ${cache} ] || [ $(($(date +%s) - $(stat -c %Y ${cache}))) -ge 2400 ]; then
	curl --connect-timeout 5 -sf https://wttr.in/${location} > ${cache}
fi

if [ ! -s ${cache} ]; then
	printf "unknown"
else
	tempnow=`sed '4q;p' ${cache} | grep -o "m\\([+-]\\)*[0-9]\\+" | \
		sed -e 's/m//g' -e 's/+//g' -e 's/$/°/' -e '1q;d' | tr '\n' ' '`
	tempfc=`sed '13q;d' ${cache} | grep -o "[+-][0-9][0-9]" | \
		sort | sed -e 's/+//g' -e 's/$/°/g' -e '1b' -e '$!d' | \
		awk 'NR==1 { a = $1 } NR==2 { print a "/" $1 }'`

	if [ -z $tempnow ] && [ -z $tempfc ]; then
		printf "unknown"
	elif [ -z $tempfc ]; then
		printf "%s" ${tempnow}
	else
		printf "%s %s" ${tempnow} ${tempfc}
	fi

	unset tempnow tempfc
fi

unset location cache
