#!/bin/sh

result="$(apropos . | dmenu -l 5 -p 'Open: ')"

if [ -n "${result}" ]; then
	page=$(echo "${result}" | grep -o '^[^(]*')
	section=$(echo "${result}" | grep -o '([^)]*)' | tr -d '()')

	st -e man ${section} ${page}
	unset page section
fi

unset result
