#!/bin/sh
## Chụp màn hình: toàn màn, 1 cửa sổ hoặc tự chọn

cmd="scrot -q 100 -z"
mode="$1"

case $1 in
	"full" | "" ) 	opts="" ;;
	"selected") 	opts="-s -f -l style=dash,width=2,opacity=25,color=#dddddd" ;;
	"window")	opts="-u -b" ;;
	*) ;;
esac

if [ ! -z $mode ]; then
	out="${HOME}/Screenshots/screenshot-${mode}-$(date +'%F_%H-%M-%S').png"
	${cmd} ${opts} ${out}
	unset out
fi

unset cmd mode opts
