[colors]
  primary.background = 	"#000000"
  primary.foreground = 	"#dddddd"
  cursor.text = 	"#000000"
  cursor.cursor = 	"#dddddd"

  normal.black = 	"#000000"
  normal.red =	 	"#e12323"
  normal.green = 	"#06a43e"
  normal.yellow = 	"#ea7300"
  normal.blue = 	"#1257d3"
  normal.magenta = 	"#c80f6b"
  normal.cyan = 	"#44a0ef"
  normal.white = 	"#dddddd"

  bright.black = 	"#5a5a5a"
  bright.red = 		"#ff4040"
  bright.green = 	"#0db755"
  bright.yellow = 	"#ff9630"
  bright.blue = 	"#2779e1"
  bright.magenta = 	"#e73f93"
  bright.cyan = 	"#7ac0fe"
  bright.white = 	"#ffffff"

[font]
  normal.family = 	"monospace"
  bold.family = 	"monospace"
  italic.family = 	"monospace"
  bold_italic.family = 	"monospace"
  size = 10

  offset.x = 0
  offset.y = 4

[window]
  decorations = "Full"
  opacity = 0.8
  padding.x = 15
  padding.y = 15

[keyboard]
  bindings = [
    { key = "Enter",	mods = "Alt|Shift", 	action = "SpawnNewInstance" },
    { key = "Up", 	mods = "Alt|Shift", 	action = "IncreaseFontSize" },
    { key = "Down", 	mods = "Alt|Shift", 	action = "DecreaseFontSize" },
    { key = "PageUp", 	mods = "Alt", 		action = "ScrollPageUp" },
    { key = "PageDown", mods = "Alt", 		action = "ScrollPageDown" },
    { key = "Up", 	mods = "Alt", 		action = "ScrollLineUp" },
    { key = "Down", 	mods = "Alt", 		action = "ScrollLineDown" },
    { key = "C", 	mods = "Alt", 		action = "Copy" },
    { key = "V", 	mods = "Alt", 		action = "Paste" },
  ]
